#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER} --dbname ${POSTGRES_DB}"

echo "Creating user: ${DB_USER_WRITE}"

$POSTGRES <<-EOSQL
CREATE USER ${DB_USER_WRITE} WITH ENCRYPTED PASSWORD '${DB_PASS_WRITE}';
EOSQL

echo "Creating user: ${DB_USER_READ}"

$POSTGRES <<-EOSQL
CREATE USER ${DB_USER_READ} WITH ENCRYPTED PASSWORD '${DB_PASS_READ}';
EOSQL

echo "Allow INSERT for: ${DB_USER_WRITE}"

$POSTGRES <<-EOSQL
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA public TO ${DB_USER_WRITE};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${DB_USER_WRITE};
EOSQL

echo "Allow SELECT for: ${DB_USER_READ}"

$POSTGRES <<-EOSQL
GRANT SELECT ON ALL TABLES IN SCHEMA public to ${DB_USER_READ};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} to ${DB_USER_READ};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public to ${DB_USER_READ};
EOSQL
