debug = true

logLevel = "DEBUG"

defaultEntryPoints = ["http"]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  swarmMode = false
  network = "proxy"

[web]
  address = ":8080"

