logLevel = "ERROR"

defaultEntryPoints = ["http"]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  swarmMode = false
  network = "proxy"

[web]
  address = ":8080"

[retry]
  attempts = 2
